services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8126:8126
    depends_on:
      mongodb:
        condition: service_healthy
    volumes:
      - ./logs:/app/logs
    env_file:
      - .env
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'

  mongodb:
    image: mongo:7.0
    volumes:
      - ./mongodb_data:/data/db
    env_file:
      - .env
    command: >
      mongod
      --wiredTigerCacheSizeGB 0.1
      --setParameter maxTransactionLockRequestTimeoutMillis=5000
      --setParameter enableLocalhostAuthBypass=false
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
        reservations:
          memory: 64M
          cpus: '0.05'
    ulimits:
      nproc: 65536
      nofile:
        soft: 20000
        hard: 40000
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.adminCommand({ ping: 1 }).ok"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 40s
    restart: unless-stopped
